const numberButtons = document.querySelectorAll(//"calculator-grid__twospan__number")
const operationButtons = document.querySelectorAll()
const equalsButton = document.querySelector()
const deleteButton = document.querySelector()
const allClearButton = document.querySelector()
const previousOperandTextElement = document.querySelector()
const currentOperandTextElement = document.querySelector()